### ISSUE TITLE
No entities

### ISSUE THREAD

**Issue by Arkie1978** [theneweinstein/thermosmart_component#15]
After installation i only see these entities:

Control setpoint------------- Onbekend
Hot water flow rate ------------Onbekend
Hot water temperature----------- Onbekend
Modulation level -------------Onbekend
Return water temperature------------Onbekend
Water pressure-------------Onbekend

No values:

I see this error in the logfile

`2022-12-14 21:40:13.541 ERROR (MainThread) [homeassistant.components.climate] Error while setting up thermosmart platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermosmart/climate.py", line 44, in async_setup_entry
    thermostat = ThermosmartThermostat(coordinator, unique_id, name)
  File "/config/custom_components/thermosmart/climate.py", line 90, in __init__
    self._attr_hvac_modes = [HVAC_MODE_AUTO, HVAC_MODE_HEAT, HVAC_MODE_COOL] if self.coordinator.data['ot']['readable']['Cooling_config'] else [HVAC_MODE_AUTO, HVAC_MODE_HEAT]
KeyError: 'ot'`

**Comment by Arkie1978** [comment]
@theneweinstein can u help me with this faults and not showing values?

Regards

**Comment by theneweinstein** [comment]
This problem occurs because you don't have OpenTherm information (this has to be enabled for your API-key by Thermosmart). However, climate should still work. I modified to code a bit, which should solve the problem (though you still won't have the sensors, only the thermostat itself). If you download the latest master branch, it should work. Unfortenately I cannot test this as I have OpenTherm enabled, could you let me know if it works, then I will create a new release with the bugfix.

**Comment by Arkie1978** [comment]
Hi, i installed the master branch and now i have a working thermostat, so you fixed the issue, thanxs a lot.

I will ask thermosmart to switch on my ot settings 

Thanxs again
