### ISSUE TITLE
api clientid/password not available anymore

### ISSUE THREAD

**Issue by turnmike2** [theneweinstein/thermosmart_component#6]
Hi,
I was really interested in your plugin for Thermosmart at HA.
Tried to follow up the info. But it looks like Thermosmart is not so fond about giving clientID's and secret passwords anymore. The official statement form the support desk is: "We do not enable the API to end customers anymore." Which leaves us in the end with a beautiful API which is not able to be used anymore, nor requested.

Then I was wondering about how the implementation of Domoticz was. For they do support it through domoticz. The strange thing is, you only need to connect through "username/password" and voila, the connection is set. Currently still using it. Domoticz code is also placed on github (domoticz/hardware/thermosmart.cpp). And I checked how they did it. It is written in c++. And I can read and understand  it a bit, but am not programmer to inject it in a decent py.
Do you have knowledge to turn the username/password into a clientid/secret? For as far as I can see  your component is the best option  for Home Assistant.

I hope you have a way/possibility to read/use the information to make it functional again.

Thanks!

**Comment by theneweinstein** [comment]
Hi,
It's unfortunate that they don't provide API keys anymore. Also Domoticz has API keys to be able to authenticate, they are hard-coded in there integration (line 267 and 268 are the client_id and secret respectively), perhaps you can try to use those.
Regards.

**Comment by TAYALE** [comment]
Those are the ones I used but since about a month it does not work anymore:

```
2020-02-10 22:05:48 ERROR (MainThread) [homeassistant.setup] Error during setup of component thermosmart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thermosmart/__init__.py", line 94, in setup
    hass.data[DOMAIN] = ThermoSmartData(token_info)
  File "/config/custom_components/thermosmart/__init__.py", line 160, in __init__
    self.thermosmart = tsmart.ThermoSmart(token=token_info['access_token'])
  File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 23, in __init__
    self.id = self._get_thermostat_id()
  File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 64, in _get_thermostat_id
    return (self._get('thermostat'))['hw']
  File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 55, in _get
    return self._internal_call('GET', url, None, payload)
  File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 50, in _internal_call
    return r.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Any clue?

Thermosmart is about a dead product. Too bad :-(

**Comment by turnmike2** [comment]
> Those are the ones I used but since about a month it does not work anymore:
> 
> ```
> 2020-02-10 22:05:48 ERROR (MainThread) [homeassistant.setup] Error during setup of component thermosmart
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
>     component.setup, hass, processed_config  # type: ignore
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/thermosmart/__init__.py", line 94, in setup
>     hass.data[DOMAIN] = ThermoSmartData(token_info)
>   File "/config/custom_components/thermosmart/__init__.py", line 160, in __init__
>     self.thermosmart = tsmart.ThermoSmart(token=token_info['access_token'])
>   File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 23, in __init__
>     self.id = self._get_thermostat_id()
>   File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 64, in _get_thermostat_id
>     return (self._get('thermostat'))['hw']
>   File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 55, in _get
>     return self._internal_call('GET', url, None, payload)
>   File "/usr/local/lib/python3.7/site-packages/thermosmart_hass/__init__.py", line 50, in _internal_call
>     return r.json()
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 889, in json
>     self.content.decode(encoding), **kwargs
>   File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> Any clue?
> 
> Thermosmart is about a dead product. Too bad :-(

Hi,
I did notice this also at least 2 times in the last 2 weeks. I was able to solve it by deleting the /config/.thermosmart-token-cache
Restarting Homeassistant and follow the installation again. As long as you do not remove the entity you'll be fine. It looks like the people at thermosmart restored and old config with old settings or something. I also enabled an ifttt connection and these settings were deleted also.

Still I think the thermosmart is working quite good. With the information mentioned by theneweinstein about using the domoticz creds, we still can enable and use this plugin. Eventhough the people behind the api are not willing to cooperate.

**Comment by TAYALE** [comment]
> I did notice this also at least 2 times in the last 2 weeks. I was able to solve it by deleting the /config/.thermosmart-token-cache
> Restarting Homeassistant and follow the installation again. As long as you do not remove the entity you'll be fine. It looks like the people at thermosmart restored and old config with old settings or something. I also enabled an ifttt connection and these settings were deleted also.

That did the trick!

**Comment by Jos-77** [comment]
Api is available again. It was die to tunnelvision on appke instead of lager picture. So not dead anymore. 

https://www.thermosmart.com/product/api/
