### ISSUE TITLE
error version date 20200522

### ISSUE THREAD

**Issue by turnmike2** [theneweinstein/thermosmart_component#8]
Hi with the current version I  am getting the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 179, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/thermosmart/climate.py", line 130, in hvac_modes
    if self._client.latest_update['ot']['readable']['Cooling_config']:
KeyError: 'ot'

Obviously the entity is not created..

Is it a coding problem? Or do I need to do something else?
Any ideas? 

Grts Michel

**Comment by mastair86** [comment]
I created a pull request to fix this issue: #9

**Comment by turnmike2** [comment]
The update worked.  Thanks. Currently using the fork from mastair86.
